apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    name: hello
spec:
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
        - name: hello
          image: vyasmus/hello-world
          imagePullPolicy: Never